#!/bin/sh
ipgess="192.168.59.123"
ipdress="192.168.59.2"

echo "
# Generated by NetworkManager
nameserver ${ipgess}
nameserver 8.8.8.8
nameserver 202.96.134.133
" >/etc/resolv.conf
echo "
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

auto eth0 
iface eth0 inet static
address  ${ipdress}
gateway  ${ipgess}
netmask  255.255.255.0
" >/etc/network/interfaces

service networking restart           

